apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ether
  name: ether-website
spec:
  ingressClassName: nginx
  rules:
    - host: ether.paris
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ether-website
                port:
                  number: 80
    - host: www.ether.paris
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ether-website
                port:
                  number: 80
