apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ether-website
  namespace: ether
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false" # Cloudflare handles HTTPS
spec:
  ingressClassName: nginx
  rules:
    - host: ether.paris
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ether-website
                port:
                  number: 80
