apiVersion: v1
kind: Service
metadata:
  namespace: ether
  name: ether-website
  labels:
    app: ether-website
spec:
  type: ClusterIP
  selector:
    app: ether-website
  ports:
    - name: http
      port: 80
      targetPort: 3000
